### ISSUE TITLE
`README`

### ISSUE THREAD

**Issue by navidcy** [dhruvbhagtani/varying-surface-forcing#2]
It'd be great if we include more information in the REAME regarding which version of the MOM5 code was used, where is the model output, which notebook produces which figures, etc.

**Comment by navidcy** [comment]
cc @dhruvbhagtani

**Comment by dhruvbhagtani** [comment]
Thanks for reminding Navid, I am procrastinating it when I probably shouldn't, as I was working on the heat transport analysis. I'll get to it next week for sure.

**Comment by navidcy** [comment]
#3 is a huge improvement!!

But it did not  fully resolve the issue here. Can you reopen it @dhruvbhagtani?

There is more information we should include for someone to reproduce the experiments. E.g. how do we construct the forcing from the ACCESS-OM2 control. Also the readme currently reads that run the control for 200 years before branching off perturbations but from what I recall we run for 100...
